import { defineComponent } from "../define.js";

export const applicationComponents = [
  defineComponent({
    slug: "app-shell",
    name: "App Shell",
    category: "application",
    selector: ".app-shell",
    className: "app-shell",
    parts: {
      content: "[data-app-content]",
      main: "[data-app-main]",
      navigation: "[data-app-navigation]",
      trigger: "[data-app-navigation-trigger]",
    },
    actionParts: { click: "trigger", focus: "trigger", press: "trigger" },
    actions: ["click", "focus", "press", "wheel"],
    events: ["a3s:app-navigation-change", "basecoat:initialized"],
    methods: [
      "closeNavigation",
      "collapseNavigation",
      "expandNavigation",
      "hideNavigation",
      "openNavigation",
      "refresh",
      "toggleNavigation",
    ],
    states: ["ready", "expanded", "collapsed", "hidden", "mobile-open"],
  }),
  defineComponent({
    slug: "app-page",
    name: "App Page",
    category: "application",
    selector: ".app-page",
    tag: "section",
    className: "app-page",
    parts: {
      action: "[data-page-actions] button, [data-page-actions] a[href]",
      actions: "[data-page-actions]",
      content: "[data-page-content]",
      identity: "[data-page-identity]",
    },
    actions: ["click", "focus", "wheel"],
    states: ["ready", "loading", "empty", "error", "permission-denied"],
  }),
  defineComponent({
    slug: "task-start",
    name: "Task Start",
    category: "harness",
    selector: ".task-start",
    tag: "section",
    className: "task-start",
    parts: {
      composer: ".agent-composer",
      suggestion: "[data-task-suggestions] button",
      suggestions: "[data-task-suggestions]",
      title: ":scope > header",
    },
    actions: ["click", "fill", "focus", "type"],
    events: ["submit"],
    states: ["ready", "loading", "offline", "disabled", "error"],
  }),
  defineComponent({
    slug: "task-workspace",
    name: "Task Workspace",
    category: "harness",
    selector: ".task-workspace",
    tag: "section",
    className: "task-workspace",
    parts: {
      composer: ".agent-composer",
      header: ":scope > .workspace-header, :scope > header",
      inspector: "[data-task-inspector]",
      inspectorTrigger: "[data-task-inspector-trigger]",
      transcript: ".agent-transcript",
    },
    actions: ["click", "fill", "focus", "press", "type", "wheel"],
    actionParts: { click: "inspectorTrigger", press: "inspectorTrigger" },
    events: ["a3s:task-inspector-change", "basecoat:initialized", "submit"],
    states: [
      "ready",
      "streaming",
      "waiting",
      "complete",
      "error",
      "inspector-open",
    ],
  }),
  defineComponent({
    slug: "catalog",
    name: "Catalog",
    category: "application",
    selector: ".catalog",
    tag: "section",
    className: "catalog",
    parts: {
      actions: "[data-catalog-actions]",
      featured: "[data-catalog-featured]",
      filter: "[data-catalog-filters] button",
      filters: "[data-catalog-filters]",
      identity: "[data-catalog-identity]",
      result: "[data-catalog-results] > *",
      results: "[data-catalog-results]",
      search: "input[type=search]",
      toolbar: "[data-catalog-toolbar]",
    },
    actions: ["click", "fill", "focus", "press", "type", "wheel"],
    events: ["input"],
    states: ["ready", "loading", "empty", "error", "partial"],
  }),
  defineComponent({
    slug: "setting-row",
    name: "Setting Row",
    category: "application",
    selector: ".setting-row",
    className: "setting-row",
    parts: {
      control:
        "[data-setting-control] input, [data-setting-control] select, [data-setting-control] textarea, [data-setting-control] button",
      controlRegion: "[data-setting-control]",
      identity: "[data-setting-identity]",
      message: "[data-setting-message]",
    },
    actions: ["check", "click", "fill", "focus", "select", "type", "uncheck"],
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid", "readonly", "loading"],
  }),
  defineComponent({
    slug: "agent-composer",
    name: "Agent Composer",
    category: "harness",
    selector: ".agent-composer",
    tag: "form",
    className: "agent-composer",
    parts: {
      action: "[data-composer-action]",
      actions: "[data-composer-actions]",
      attachment:
        "[data-composer-resources] > li, [data-composer-context] > li",
      context: "[data-composer-resources], [data-composer-context]",
      editor: "[data-composer-editor]",
      input: "[data-composer-input]",
      menu: "[data-composer-suggestions]",
      option:
        "[data-composer-suggestions] [role=option], [data-composer-suggestions] [role=treeitem]",
      queue: "[data-composer-queue]",
      queueItem: "[data-composer-queue] li",
      setting: "[data-composer-setting]",
      status: "[data-composer-status]",
      submit: "button[type=submit]",
      tools: "[data-composer-tools]",
    },
    actions: ["click", "fill", "focus", "press", "select", "type"],
    actionParts: {
      click: "action",
      fill: "input",
      focus: "input",
      press: "input",
      select: "setting",
      type: "input",
    },
    methods: [
      "clearDraft",
      "closeSuggestions",
      "focusInput",
      "getDraft",
      "getState",
      "openSuggestions",
      "refresh",
      "runAction",
      "setDraft",
      "setError",
      "setState",
    ],
    hooks: [
      "a3s:composer-before-action",
      "a3s:composer-before-submit",
    ],
    events: [
      "a3s:composer-action",
      "a3s:composer-before-action",
      "a3s:composer-before-submit",
      "a3s:composer-draft-change",
      "a3s:composer-queue-action",
      "a3s:composer-state-change",
      "a3s:composer-submit",
      "a3s:composer-trigger-change",
      "input",
      "submit",
      "basecoat:initialized",
    ],
    states: [
      "ready",
      "submitting",
      "streaming",
      "queued",
      "stopping",
      "loading",
      "offline",
      "error",
      "disabled",
      "invalid",
    ],
  }),
  defineComponent({
    slug: "agent-transcript",
    name: "Agent Transcript",
    category: "harness",
    selector: ".agent-transcript",
    tag: "section",
    className: "agent-transcript",
    parts: {
      message: "[data-transcript-viewport] > li",
      status: "[data-transcript-status]",
      viewport: "[data-transcript-viewport]",
    },
    actions: ["click", "focus", "wheel"],
    states: ["ready", "streaming", "waiting", "complete", "error", "empty"],
  }),
  defineComponent({
    slug: "agent-workbench",
    name: "Agent Workbench",
    category: "harness",
    selector: ".agent-workbench",
    tag: "section",
    className: "agent-workbench",
    parts: {
      activity: "[data-agent-activity]",
      canvas: "[data-agent-canvas]",
      context: "[data-agent-context]",
      inspector: "[data-agent-inspector]",
    },
    actions: ["click", "fill", "focus", "press", "select", "type", "wheel"],
    states: [
      "ready",
      "running",
      "waiting",
      "complete",
      "error",
      "inspector-open",
      "context-open",
    ],
  }),
  defineComponent({
    slug: "approval-request",
    name: "Approval Request",
    category: "harness",
    selector: ".approval-request",
    tag: "section",
    className: "approval-request",
    parts: {
      action: "button",
      approve: "button[type=submit], [data-approval=approve]",
      deny: "[data-approval=deny]",
      scope: "input[type=radio]",
      title: ":scope > header :is(h2, h3, h4)",
    },
    actions: ["check", "click", "focus", "press"],
    events: ["submit"],
    states: ["pending", "approved", "denied", "expired", "error"],
  }),
  defineComponent({
    slug: "execution-item",
    name: "Execution Item",
    category: "harness",
    selector: ".execution-item",
    tag: "details",
    className: "execution-item",
    parts: {
      content: ":scope > :not(summary)",
      disclosure: "[data-execution-disclosure]",
      status: "[data-execution-status]",
      trigger: ":scope > summary",
    },
    actions: ["click", "focus", "press"],
    events: ["toggle"],
    states: ["queued", "running", "waiting", "success", "cancelled", "error"],
  }),
  defineComponent({
    slug: "brand-lockup",
    name: "Brand Lockup",
    category: "application",
    selector: ".brand-lockup",
    tag: "a",
    className: "brand-lockup",
    parts: {
      description: "[data-brand-description]",
      identity: "[data-brand-identity]",
      mark: "[data-brand-mark]",
      name: "[data-brand-name]",
    },
    actions: ["click", "focus"],
    states: ["ready"],
  }),
  defineComponent({
    slug: "workspace-header",
    name: "Workspace Header",
    category: "application",
    selector: ".workspace-header",
    tag: "header",
    className: "workspace-header",
    parts: {
      action:
        "[data-workspace-actions] button, [data-workspace-actions] a[href]",
      actions: "[data-workspace-actions]",
      identity: "[data-workspace-identity]",
      leading: "[data-workspace-leading]",
    },
    actions: ["click", "focus"],
    states: ["ready", "busy", "offline"],
  }),
  defineComponent({
    slug: "toolbar",
    name: "Toolbar",
    category: "application",
    selector: ".toolbar",
    className: "toolbar",
    attributes: { role: "toolbar" },
    parts: { action: "button, a[href]", group: "[role=group]" },
    actions: ["click", "focus", "press"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "ribbon",
    name: "Ribbon",
    category: "application",
    selector: ".ribbon",
    className: "ribbon",
    parts: {
      action: "[role=tabpanel] button",
      panel: "[role=tabpanel]",
      tab: "[role=tab]",
      tablist: "[role=tablist]",
    },
    actions: ["click", "focus", "press"],
    events: ["basecoat:initialized"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "settings-layout",
    name: "Settings Layout",
    category: "application",
    selector: ".settings-layout",
    className: "settings-layout",
    parts: {
      content: ":scope > main",
      navigation: ":scope > aside nav",
      section: ":scope > main > section",
    },
    actions: ["click", "focus", "wheel"],
    states: ["ready", "loading", "error"],
  }),
  defineComponent({
    slug: "resource-card",
    name: "Resource Card",
    category: "application",
    selector: ".resource-card",
    tag: "article",
    className: "resource-card",
    parts: {
      action: "button, a[href]",
      content: ":scope > section",
      media: ":scope > figure",
      status: ".status-badge, [data-resource-status]",
    },
    actions: ["click", "focus", "press"],
    states: [
      "ready",
      "selected",
      "installed",
      "unavailable",
      "loading",
      "error",
    ],
  }),
  defineComponent({
    slug: "split-pane",
    name: "Split Pane",
    category: "application",
    selector: ".split-pane",
    className: "split-pane",
    parts: {
      end: ":scope > section:last-of-type",
      separator: "[role=separator]",
      start: ":scope > section:first-of-type",
    },
    actions: ["drag", "focus", "press"],
    events: ["a3s:split-change", "basecoat:initialized"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "task-pane",
    name: "Task Pane",
    category: "application",
    selector: ".task-pane",
    tag: "aside",
    className: "task-pane",
    parts: {
      action: "button",
      content: ":scope > section",
      field: ".field",
      header: ":scope > header",
    },
    actions: ["click", "fill", "focus", "select", "type", "wheel"],
    states: ["ready", "open", "closed", "loading", "error"],
  }),
  defineComponent({
    slug: "status-bar",
    name: "Status Bar",
    category: "application",
    selector: ".status-bar",
    className: "status-bar",
    parts: {
      action: "[data-status-actions] button, [data-status-actions] input",
      actions: "[data-status-actions]",
      info: "[data-status-info]",
    },
    actions: ["click", "focus", "press"],
    states: ["ready", "busy", "offline", "error"],
  }),
  defineComponent({
    slug: "task-plan",
    name: "Task Plan",
    category: "harness",
    selector: ".task-plan",
    tag: "section",
    className: "task-plan",
    parts: {
      action: ":scope > footer button, :scope > footer a[href]",
      progress: ":scope > header [role=progressbar]",
      status: ":scope > header [data-plan-status]",
      step: ":scope > ol > .plan-step",
      steps: ":scope > ol",
      title: ":scope > header :is(h2, h3)",
    },
    actions: ["click", "focus", "wheel"],
    states: ["draft", "active", "paused", "complete", "error"],
  }),
  defineComponent({
    slug: "plan-step",
    name: "Plan Step",
    category: "harness",
    selector: ".plan-step",
    tag: "li",
    className: "plan-step",
    parts: {
      action: "button, a[href]",
      description: "[data-step-description]",
      marker: "[data-plan-marker]",
      status: "[data-plan-step-status]",
      title: "[data-step-identity] :is(h3, h4, strong)",
    },
    actions: ["click", "focus"],
    states: ["pending", "active", "complete", "blocked", "error", "skipped"],
  }),
  defineComponent({
    slug: "message-status",
    name: "Message Status",
    category: "harness",
    selector: ".message-status",
    tag: "output",
    className: "message-status",
    parts: {
      indicator: "[data-message-status-indicator]",
      label: "[data-message-status-label]",
      metadata: "time, [data-message-status-meta]",
    },
    states: ["sending", "streaming", "sent", "queued", "stopped", "error"],
  }),
  defineComponent({
    slug: "message-attachment",
    name: "Message Attachment",
    category: "harness",
    selector: ".message-attachment",
    tag: "article",
    className: "message-attachment",
    parts: {
      action: "button, a[href]",
      media: ":scope > figure",
      metadata: "[data-attachment-meta]",
      title: "[data-attachment-identity] :is(h3, h4, strong)",
    },
    actions: ["click", "focus"],
    states: ["ready", "uploading", "complete", "missing", "error"],
  }),
  defineComponent({
    slug: "message-citation",
    name: "Message Citation",
    category: "harness",
    selector: ".message-citation",
    tag: "a",
    className: "message-citation",
    attributes: { href: "#" },
    parts: {
      index: "[data-citation-index]",
      source: "[data-citation-source]",
      title: "[data-citation-title]",
    },
    actions: ["click", "focus"],
    states: ["ready", "visited", "unavailable", "error"],
  }),
  defineComponent({
    slug: "artifact-card",
    name: "Artifact Card",
    category: "harness",
    selector: ".artifact-card",
    tag: "article",
    className: "artifact-card",
    parts: {
      action: ":scope > footer button, :scope > footer a[href]",
      content: ":scope > section",
      metadata: "[data-artifact-meta]",
      preview: "[data-artifact-preview]",
      title: ":scope > header :is(h3, h4, strong)",
    },
    actions: ["click", "focus"],
    states: ["ready", "generating", "complete", "stale", "error"],
  }),
  defineComponent({
    slug: "context-selector",
    name: "Context Selector",
    category: "harness",
    selector: ".context-selector",
    tag: "label",
    className: "context-selector",
    parts: {
      control: "select, button[aria-haspopup]",
      description: "[data-context-description]",
      label: "[data-context-label]",
    },
    actions: ["click", "focus", "select"],
    events: ["change", "input"],
    states: ["ready", "loading", "disabled", "invalid", "unavailable"],
  }),
  defineComponent({
    slug: "task-queue",
    name: "Task Queue",
    category: "harness",
    selector: ".task-queue",
    tag: "section",
    className: "task-queue",
    parts: {
      action: "[data-queue-actions] button, [data-queue-actions] a[href]",
      item: ":scope > ol > li",
      list: ":scope > ol",
      status: "[data-queue-status]",
      title: ":scope > header :is(h2, h3)",
    },
    actions: ["click", "focus", "wheel"],
    states: ["idle", "running", "paused", "blocked", "complete", "error"],
  }),
  defineComponent({
    slug: "checkpoint",
    name: "Checkpoint",
    category: "harness",
    selector: ".checkpoint",
    tag: "article",
    className: "checkpoint",
    parts: {
      action: ":scope > footer button, :scope > footer a[href]",
      details: ":scope > section",
      metadata: "[data-checkpoint-meta]",
      title: ":scope > header :is(h3, h4, strong)",
    },
    actions: ["click", "focus"],
    states: ["saving", "saved", "restoring", "restored", "expired", "error"],
  }),
  defineComponent({
    slug: "follow-up-suggestions",
    name: "Follow-up Suggestions",
    category: "harness",
    selector: ".follow-up-suggestions",
    tag: "nav",
    className: "follow-up-suggestions",
    attributes: { "aria-label": "Suggested follow-up actions" },
    parts: {
      action: "button, a[href]",
      list: ":scope > ul",
      title: ":scope > :is(h2, h3, strong)",
    },
    actions: ["click", "focus"],
    states: ["ready", "loading", "empty", "disabled"],
  }),
  defineComponent({
    slug: "tool-call",
    name: "Tool Call",
    category: "harness",
    selector: ".tool-call",
    tag: "details",
    className: "tool-call",
    parts: {
      action: "[data-tool-action]",
      args: "[data-tool-args], [data-tool-input]",
      content: "[data-tool-content]",
      duration: "[data-tool-duration]",
      error: "[data-tool-error]",
      input: "[data-tool-input]",
      operation: "[data-tool-operation]",
      output: "[data-tool-output]",
      progress: "[data-tool-progress]",
      status: "[data-tool-status]",
      trigger: ":scope > summary",
    },
    actions: ["click", "focus", "press", "wheel"],
    methods: [
      "appendOutput",
      "close",
      "getState",
      "openCall",
      "refresh",
      "runAction",
      "setOutput",
      "setProgress",
      "setState",
      "toggle",
    ],
    hooks: ["a3s:tool-before-action"],
    events: [
      "a3s:tool-action",
      "a3s:tool-before-action",
      "a3s:tool-output-change",
      "a3s:tool-state-change",
      "basecoat:initialized",
      "toggle",
    ],
    states: [
      "preparing",
      "awaiting",
      "running",
      "succeeded",
      "failed",
      "denied",
      "timed-out",
      "interrupted",
      "queued",
      "waiting",
      "success",
      "cancelled",
      "error",
    ],
  }),
  defineComponent({
    slug: "tool-call-timeline",
    name: "Tool Call Timeline",
    category: "harness",
    selector: ".tool-call-timeline",
    tag: "section",
    className: "tool-call-timeline",
    parts: {
      action: "[data-tool-timeline-action]",
      call: "[data-tool-call-list] > li > .tool-call",
      list: "[data-tool-call-list]",
      status: "[data-tool-timeline-status]",
      summary: "[data-tool-timeline-summary]",
    },
    actions: ["click", "focus", "press", "wheel"],
    methods: [
      "collapseHistory",
      "expandHistory",
      "getSummary",
      "refresh",
    ],
    events: [
      "a3s:tool-timeline-change",
      "a3s:tool-timeline-visibility-change",
      "basecoat:initialized",
    ],
    states: ["idle", "running", "attention", "problem", "complete"],
  }),
  defineComponent({
    slug: "tool-result",
    name: "Tool Result",
    category: "harness",
    selector: ".tool-result.tabs",
    tag: "section",
    className: "tool-result tabs",
    parts: {
      action: "[data-tool-result-actions] button, [data-tool-result-actions] a[href]",
      content: "[role=tabpanel]",
      metadata: "[data-tool-result-meta]",
      status: "[data-tool-result-status]",
      tab: "[role=tab]",
      tablist: "[role=tablist]",
    },
    actions: ["click", "focus", "press", "wheel"],
    methods: ["refresh", "select"],
    hooks: ["a3s:tabs-before-change"],
    events: [
      "a3s:tabs-before-change",
      "a3s:tabs-change",
      "basecoat:initialized",
    ],
    states: ["ready", "loading", "empty", "error"],
  }),
  defineComponent({
    slug: "change-review",
    name: "Change Review",
    category: "harness",
    selector: ".change-review",
    tag: "section",
    className: "change-review",
    parts: {
      action: ":scope > footer button, :scope > footer a[href]",
      delta: "[data-review-delta]",
      file: "[data-review-files] > li",
      files: "[data-review-files]",
      status: ".status-badge, [data-review-status]",
      summary: "[data-review-summary]",
      title: ":scope > header :is(h2, h3)",
    },
    actions: ["click", "focus", "press", "wheel"],
    states: [
      "pending",
      "reviewing",
      "accepted",
      "rejected",
      "conflict",
      "error",
    ],
  }),
  defineComponent({
    slug: "terminal",
    name: "Terminal",
    category: "harness",
    selector: ".terminal",
    tag: "section",
    className: "terminal",
    parts: {
      action: ":scope > header button, :scope > footer button",
      command: "[data-terminal-command]",
      output: "[data-terminal-output]",
      status: "[data-terminal-status]",
      title: ":scope > header :is(h2, h3, strong)",
    },
    actions: ["click", "focus", "press", "wheel"],
    states: ["idle", "running", "waiting", "success", "cancelled", "error"],
  }),
  defineComponent({
    slug: "execution-evidence",
    name: "Execution Evidence",
    category: "harness",
    selector: ".execution-evidence",
    tag: "article",
    className: "execution-evidence",
    parts: {
      action: ":scope > footer button, :scope > footer a[href]",
      content: ":scope > section",
      metadata: "[data-evidence-meta]",
      result: "[data-evidence-result]",
      title: ":scope > header :is(h3, h4, strong)",
    },
    actions: ["click", "focus"],
    states: ["capturing", "verified", "unverified", "expired", "error"],
  }),
];
