import { defineComponent } from "../define.js";

export const contentComponents = [
  defineComponent({
    slug: "code-diff",
    name: "Code Diff",
    category: "data-display",
    selector: ".code-diff",
    tag: "figure",
    className: "code-diff",
    parts: {
      code: "pre, code",
      header: ":scope > figcaption, :scope > header",
      line: "[data-diff-line]",
      marker: "[data-diff-marker]",
      newLine: "[data-diff-new-line]",
      oldLine: "[data-diff-old-line]",
    },
    actions: ["focus", "wheel"],
    actionParts: { focus: "code", wheel: "code" },
    states: ["ready", "loading", "empty", "error"],
  }),
  defineComponent({
    slug: "color-swatches",
    name: "Color Swatches",
    category: "forms",
    selector: ".color-swatches",
    tag: "fieldset",
    className: "color-swatches",
    parts: {
      input: "input[type=radio], input[type=checkbox]",
      label: "label",
      swatch: "[data-swatch]",
    },
    actions: ["check", "click", "focus", "select"],
    actionParts: {
      check: "input",
      click: "label",
      focus: "input",
      select: "input",
    },
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid"],
  }),
  defineComponent({
    slug: "file-type-icon",
    name: "File Type Icon",
    category: "data-display",
    selector: ".file-type-icon",
    tag: "span",
    className: "file-type-icon",
    parts: { extension: "[data-file-extension]", graphic: "svg, img" },
    states: ["ready", "generic", "known", "host-provided"],
  }),
  defineComponent({
    slug: "highlighter",
    name: "Highlighter",
    category: "data-display",
    selector: ".highlighter",
    tag: "pre",
    className: "highlighter",
    attributes: { tabindex: "0" },
    parts: {
      code: "code",
      line: "[data-code-line]",
      mark: "mark, [data-highlighted]",
      token: "[data-code-token]",
    },
    actions: ["focus", "wheel"],
    states: ["ready", "loading", "error"],
  }),
  defineComponent({
    slug: "icon",
    name: "Icon",
    category: "data-display",
    selector: ".icon",
    tag: "span",
    className: "icon",
    parts: { graphic: "svg, img, [data-icon-slot]" },
    states: ["ready", "decorative", "labeled", "host-provided"],
  }),
  defineComponent({
    slug: "image",
    name: "Image",
    category: "data-display",
    selector: "figure.image",
    tag: "figure",
    className: "image",
    parts: {
      caption: "figcaption",
      image: "img, picture",
      status: "[data-image-status]",
    },
    states: ["loading", "ready", "error"],
  }),
  defineComponent({
    slug: "image-select",
    name: "Image Select",
    category: "forms",
    selector: ".image-select",
    tag: "fieldset",
    className: "image-select",
    parts: {
      image: "img, [data-image-preview]",
      input: "input[type=radio], input[type=checkbox]",
      label: "label",
      option: "[data-image-option]",
    },
    actions: ["check", "click", "focus", "select"],
    actionParts: {
      check: "input",
      click: "label",
      focus: "input",
      select: "input",
    },
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid"],
  }),
  defineComponent({
    slug: "markdown-surface",
    name: "Markdown Surface",
    category: "data-display",
    selector: ".markdown-surface",
    tag: "article",
    className: "markdown-surface",
    parts: {
      code: "pre, code",
      link: "a[href]",
      media: "figure, img, video",
      renderer: "[data-markdown-renderer]",
    },
    actions: ["click", "focus", "wheel"],
    actionParts: { click: "link", focus: "link", wheel: "code" },
    states: ["ready", "loading", "empty", "error"],
  }),
  defineComponent({
    slug: "snippet",
    name: "Snippet",
    category: "data-display",
    selector: ".snippet",
    className: "snippet",
    parts: { code: "code", copy: ".copy-button, [data-copy-button]" },
    actions: ["click", "focus", "wheel"],
    actionParts: { click: "copy", focus: "copy", wheel: "code" },
    states: ["ready", "copied", "error"],
  }),
  defineComponent({
    slug: "streaming-text",
    name: "Streaming Text",
    category: "feedback",
    selector: ".streaming-text",
    tag: "output",
    className: "streaming-text",
    attributes: { "aria-live": "polite" },
    parts: {
      content: "[data-streaming-content]",
      status: "[data-streaming-status]",
    },
    events: [
      "a3s:streaming-text-complete",
      "a3s:streaming-text-update",
      "basecoat:initialized",
    ],
    methods: ["append", "complete", "getState", "setText"],
    states: ["streaming", "complete", "paused", "error"],
  }),
];
