import { defineComponent } from "../define.js";

export const feedbackComponents = [
  defineComponent({
    slug: "alert",
    name: "Alert",
    category: "feedback",
    selector: ".alert",
    className: "alert",
    attributes: { role: "alert" },
    parts: {
      action: ":scope > footer",
      description: "p",
      title: "h2, h3, strong",
    },
    states: ["ready", "info", "success", "warning", "destructive"],
  }),
  defineComponent({
    slug: "badge",
    name: "Badge",
    category: "feedback",
    selector: ".badge",
    tag: "span",
    className: "badge",
    states: ["ready", "secondary", "outline", "destructive"],
  }),
  defineComponent({
    slug: "status-badge",
    name: "Status Badge",
    category: "feedback",
    selector: ".status-badge",
    tag: "span",
    className: "status-badge",
    parts: { indicator: "[data-indicator]" },
    states: ["neutral", "active", "success", "warning", "danger"],
  }),
  defineComponent({
    slug: "empty",
    name: "Empty",
    category: "feedback",
    selector: ".empty",
    tag: "section",
    className: "empty",
    parts: {
      action: "button, a[href]",
      description: "p",
      icon: "figure",
      title: "h2, h3",
    },
    actions: ["click", "focus"],
    states: ["empty", "error", "permission-denied", "offline"],
  }),
  defineComponent({
    slug: "progress",
    name: "Progress",
    category: "feedback",
    selector: ".progress",
    className: "progress",
    attributes: {
      "aria-valuemax": "100",
      "aria-valuemin": "0",
      "aria-valuenow": "0",
      role: "progressbar",
    },
    parts: { indicator: ":scope > span" },
    states: ["ready", "complete", "indeterminate"],
  }),
  defineComponent({
    slug: "skeleton",
    name: "Skeleton",
    category: "feedback",
    selector: ".skeleton",
    className: "skeleton",
    attributes: { "aria-hidden": "true" },
    states: ["loading"],
  }),
  defineComponent({
    slug: "spinner",
    name: "Spinner",
    category: "feedback",
    selector: ".animate-spin[role=status]",
    tag: "span",
    className: "animate-spin",
    attributes: { "aria-label": "Loading", role: "status" },
    states: ["loading"],
  }),
  defineComponent({
    slug: "toast",
    name: "Toast",
    category: "feedback",
    selector: ".toast",
    className: "toast",
    attributes: { role: "status" },
    parts: { action: "button, a[href]", description: "p", title: "strong" },
    actions: ["click", "focus"],
    events: ["basecoat:initialized"],
    states: ["open", "closing", "closed", "success", "warning", "danger"],
  }),
];

export const dataComponents = [
  defineComponent({
    slug: "accordion",
    name: "Accordion",
    category: "data-display",
    selector: ".accordion",
    tag: "section",
    className: "accordion",
    parts: {
      item: ":scope > details",
      panel: ":scope > details > :not(summary)",
      trigger: ":scope > details > summary",
    },
    actions: ["click", "focus", "press"],
    events: ["basecoat:initialized", "toggle"],
    states: ["ready", "open", "closed", "disabled"],
  }),
  defineComponent({
    slug: "avatar",
    name: "Avatar",
    category: "data-display",
    selector: ".avatar",
    tag: "span",
    className: "avatar",
    parts: { fallback: ":scope > span", image: "img" },
    states: ["ready", "fallback"],
  }),
  defineComponent({
    slug: "card",
    name: "Card",
    category: "data-display",
    selector: ".card",
    className: "card",
    parts: {
      action: ".card-action, :scope > footer",
      content: ":scope > section",
      header: ":scope > header",
    },
    actions: ["click", "focus"],
    states: ["ready", "selected", "disabled"],
  }),
  defineComponent({
    slug: "chart",
    name: "Chart",
    category: "data-display",
    selector: ".chart, .a3s-chart-demo",
    className: "chart",
    parts: { canvas: "canvas", legend: "+ .chart-legend" },
    actions: ["focus", "hover"],
    actionParts: { focus: "canvas", hover: "canvas" },
    events: ["a3s:themechange"],
    states: ["ready", "loading", "empty", "error"],
  }),
  defineComponent({
    slug: "data-grid",
    name: "Data Grid",
    category: "data-display",
    selector: ".data-grid",
    tag: "section",
    className: "data-grid",
    parts: {
      action: "[data-grid-actions] button, [data-grid-actions] a[href]",
      bulkActions: ":scope > .bulk-action-bar",
      row: "tbody > tr",
      select: "input[data-grid-select], input[data-grid-select-all]",
      sort: "[data-grid-sort]",
      table: "table",
      viewport: "[data-grid-viewport]",
    },
    actions: ["check", "click", "focus", "press", "wheel"],
    actionParts: {
      check: "select",
      click: "action",
      focus: "sort",
      press: "sort",
      wheel: "viewport",
    },
    events: [
      "a3s:data-grid-selection-change",
      "a3s:data-grid-sort",
      "basecoat:initialized",
    ],
    states: ["ready", "loading", "empty", "error", "partial", "selected"],
  }),
  defineComponent({
    slug: "item",
    name: "Item",
    category: "data-display",
    selector: ".item",
    tag: "article",
    className: "item",
    parts: {
      action: ":scope > aside, button, a[href]",
      content: ":scope > section",
      media: ":scope > figure",
    },
    actions: ["click", "focus"],
    states: ["ready", "selected", "disabled"],
  }),
  defineComponent({
    slug: "kbd",
    name: "Kbd",
    category: "data-display",
    selector: ".kbd",
    tag: "kbd",
    className: "kbd",
    states: ["ready"],
  }),
  defineComponent({
    slug: "log-viewer",
    name: "Log Viewer",
    category: "harness",
    selector: ".log-viewer",
    tag: "section",
    className: "log-viewer",
    attributes: { role: "log" },
    parts: {
      filter: "[data-log-actions] button, [data-log-filter]",
      gap: "[data-log-gap]",
      record: "[data-log-record]",
      viewport: "[data-log-viewport], [role=log]",
    },
    actions: ["click", "focus", "press", "wheel"],
    actionParts: {
      click: "filter",
      focus: "filter",
      press: "filter",
      wheel: "viewport",
    },
    states: ["ready", "streaming", "paused", "error", "empty"],
  }),
  defineComponent({
    slug: "property-list",
    name: "Property List",
    category: "data-display",
    selector: ".property-list",
    tag: "dl",
    className: "property-list",
    parts: { item: ":scope > div", label: "dt", value: "dd" },
    states: ["ready", "empty"],
  }),
  defineComponent({
    slug: "table",
    name: "Table",
    category: "data-display",
    selector: ".table-container",
    className: "table-container",
    parts: {
      body: "tbody",
      caption: "caption",
      control: "input, button, a[href]",
      header: "thead",
      row: "tbody > tr",
      table: "table",
    },
    actions: ["check", "click", "focus", "wheel"],
    actionParts: {
      check: "control",
      click: "control",
      focus: "control",
      wheel: "table",
    },
    events: ["change"],
    states: ["ready", "loading", "empty", "error"],
  }),
  defineComponent({
    slug: "stepper",
    name: "Stepper",
    category: "data-display",
    selector: ".stepper",
    tag: "ol",
    className: "stepper",
    parts: { item: ":scope > li", marker: "[data-step-marker]" },
    actions: ["focus", "wheel"],
    states: ["ready", "active", "success", "warning", "danger"],
  }),
  defineComponent({
    slug: "timeline",
    name: "Timeline",
    category: "data-display",
    selector: ".timeline",
    tag: "ol",
    className: "timeline",
    parts: { item: ":scope > li", marker: "[data-marker]" },
    states: ["ready", "active", "success", "warning", "danger"],
  }),
  defineComponent({
    slug: "tree",
    name: "Tree",
    category: "data-display",
    selector: ".tree",
    className: "tree",
    attributes: { role: "tree" },
    parts: {
      item: "[role=treeitem]",
      label: "[data-tree-label]",
      row: "[data-tree-row]",
    },
    actions: ["click", "focus", "press", "select"],
    actionParts: { click: "row", focus: "row", press: "row", select: "row" },
    events: ["a3s:tree-toggle", "basecoat:initialized"],
    states: ["ready", "selected", "expanded", "collapsed", "disabled"],
  }),
];
