import { defineComponent } from "../define.js";

export const harnessComponents = [
  defineComponent({
    slug: "file-explorer",
    name: "File Explorer",
    category: "harness",
    selector: ".file-explorer",
    tag: "section",
    className: "file-explorer",
    parts: {
      action:
        "[data-file-explorer-actions] button, [data-file-explorer-toolbar] button",
      input: "[data-file-explorer-search], [data-file-editor]",
      state: "[data-file-explorer-state]",
      status: "[data-file-status], [data-file-dirty]",
      toolbar: "[data-file-explorer-toolbar]",
      tree: ".tree[role=tree]",
      viewport: "[data-file-explorer-viewport]",
    },
    actions: ["click", "fill", "focus", "press", "select", "type", "wheel"],
    actionParts: {
      click: "action",
      fill: "input",
      focus: "input",
      press: "action",
      select: "tree",
      type: "input",
      wheel: "viewport",
    },
    methods: [
      "beginRename",
      "cancelRename",
      "clearFilter",
      "commitRename",
      "getFilter",
      "getSelection",
      "getState",
      "refresh",
      "runAction",
      "select",
      "setFilter",
      "setReadonly",
      "setRenameError",
      "setState",
    ],
    hooks: [
      "a3s:file-before-action",
      "a3s:file-before-filter-change",
      "a3s:file-before-rename",
      "a3s:file-before-selection-change",
    ],
    events: [
      "a3s:context-menu-select",
      "a3s:file-action",
      "a3s:file-before-action",
      "a3s:file-before-filter-change",
      "a3s:file-before-rename",
      "a3s:file-before-selection-change",
      "a3s:file-filter-change",
      "a3s:file-rename",
      "a3s:file-rename-cancel",
      "a3s:file-selection-change",
      "a3s:file-state-change",
      "a3s:tree-toggle",
      "basecoat:initialized",
    ],
    states: [
      "ready",
      "loading",
      "empty",
      "error",
      "permission-denied",
      "readonly",
      "renaming",
    ],
  }),
  defineComponent({
    slug: "file-manager",
    name: "File Manager",
    category: "harness",
    selector: ".file-manager",
    tag: "section",
    className: "file-manager",
    parts: {
      action: "[data-file-action]",
      item: "[data-file-item]",
      navigation: "[data-file-manager-navigation]",
      preview: "[data-file-manager-preview]",
      search: "[data-file-manager-search] input, input[data-file-manager-search]",
      selection: "[data-file-manager-selection]",
      state: "[data-file-manager-state]",
      status: "[data-file-manager-status]",
      toolbar: "[data-file-manager-toolbar]",
      viewport: "[data-file-manager-viewport]",
    },
    actions: ["click", "fill", "focus", "press", "select", "type", "wheel"],
    actionParts: {
      click: "action",
      fill: "search",
      focus: "item",
      press: "item",
      select: "item",
      type: "search",
      wheel: "viewport",
    },
    methods: [
      "clearFilter",
      "clearSelection",
      "closePreview",
      "getFilter",
      "getSelection",
      "getState",
      "getView",
      "openPreview",
      "refresh",
      "runAction",
      "select",
      "setFilter",
      "setReadonly",
      "setState",
      "setView",
    ],
    hooks: [
      "a3s:file-manager-before-action",
      "a3s:file-manager-before-filter-change",
      "a3s:file-manager-before-selection-change",
    ],
    events: [
      "a3s:file-manager-action",
      "a3s:file-manager-before-action",
      "a3s:file-manager-before-filter-change",
      "a3s:file-manager-before-selection-change",
      "a3s:file-manager-filter-change",
      "a3s:file-manager-preview-change",
      "a3s:file-manager-selection-change",
      "a3s:file-manager-state-change",
      "a3s:file-manager-view-change",
      "basecoat:initialized",
    ],
    states: [
      "ready",
      "loading",
      "empty",
      "partial",
      "error",
      "offline",
      "permission-denied",
      "readonly",
    ],
  }),
  defineComponent({
    slug: "knowledge-library",
    name: "Knowledge Library",
    category: "harness",
    selector: ".knowledge-library",
    tag: "section",
    className: "knowledge-library",
    parts: {
      action: "[data-knowledge-action]",
      detail: "[data-knowledge-library-detail]",
      filter: "[data-knowledge-filter]",
      item: "[data-knowledge-item]",
      navigation: "[data-knowledge-library-navigation]",
      search:
        "[data-knowledge-library-search] input, input[data-knowledge-library-search]",
      state: "[data-knowledge-library-state]",
      status: "[data-knowledge-library-status]",
      viewport: "[data-knowledge-library-viewport]",
    },
    actions: ["click", "fill", "focus", "press", "select", "type", "wheel"],
    actionParts: {
      click: "action",
      fill: "search",
      focus: "item",
      press: "item",
      select: "item",
      type: "search",
      wheel: "viewport",
    },
    methods: [
      "clearFilter",
      "clearSelection",
      "getFilter",
      "getSelection",
      "getState",
      "refresh",
      "runAction",
      "select",
      "setFilter",
      "setPhase",
      "setState",
    ],
    hooks: [
      "a3s:knowledge-before-action",
      "a3s:knowledge-before-filter-change",
      "a3s:knowledge-before-selection-change",
    ],
    events: [
      "a3s:knowledge-action",
      "a3s:knowledge-before-action",
      "a3s:knowledge-before-filter-change",
      "a3s:knowledge-before-selection-change",
      "a3s:knowledge-filter-change",
      "a3s:knowledge-phase-change",
      "a3s:knowledge-selection-change",
      "a3s:knowledge-state-change",
      "basecoat:initialized",
    ],
    states: [
      "ready",
      "loading",
      "empty",
      "partial",
      "error",
      "offline",
      "permission-denied",
    ],
  }),
  defineComponent({
    slug: "code-graph",
    name: "Code Graph",
    category: "harness",
    selector: ".code-graph",
    tag: "section",
    className: "code-graph",
    parts: {
      action: "[data-code-graph-action]",
      canvas: "[data-code-graph-canvas]",
      edge: "[data-code-edge]",
      inspector: "[data-code-graph-inspector]",
      legend: "[data-code-graph-legend]",
      list: "[data-code-graph-list]",
      node: "[data-code-node]",
      search: "[data-code-graph-search]",
      status: "[data-code-graph-status]",
      viewport: "[data-code-graph-viewport]",
    },
    actions: ["click", "fill", "focus", "press", "type", "wheel"],
    actionParts: {
      click: "action",
      fill: "search",
      focus: "viewport",
      press: "viewport",
      type: "search",
      wheel: "viewport",
    },
    methods: [
      "clearFilter",
      "clearSelection",
      "getFilter",
      "getSelection",
      "getState",
      "refresh",
      "resetView",
      "select",
      "setData",
      "setFilter",
      "setState",
      "setView",
      "zoomIn",
      "zoomOut",
    ],
    hooks: [
      "a3s:code-graph-before-filter-change",
      "a3s:code-graph-before-selection-change",
    ],
    events: [
      "a3s:code-graph-before-filter-change",
      "a3s:code-graph-before-selection-change",
      "a3s:code-graph-filter-change",
      "a3s:code-graph-selection-change",
      "a3s:code-graph-state-change",
      "a3s:code-graph-view-change",
      "basecoat:initialized",
    ],
    states: [
      "ready",
      "loading",
      "empty",
      "error",
      "unsupported",
      "partial",
    ],
  }),
  defineComponent({
    slug: "device-simulator",
    name: "Device Simulator",
    category: "harness",
    selector: ".device-simulator",
    tag: "section",
    className: "device-simulator",
    parts: {
      action:
        "[data-device-simulator-actions] button, [data-device-simulator-navigation] button, :scope > footer button",
      command: "[data-device-simulator-command]",
      control:
        "[data-device-simulator-select], [data-device-simulator-width], [data-device-simulator-height], [data-device-simulator-orientation] button",
      input: "[data-device-simulator-url]",
      preview: "[data-device-simulator-preview]",
      status:
        "[data-device-simulator-status], [data-device-simulator-screen-status]",
      viewport: "[data-device-simulator-workspace]",
    },
    actionParts: {
      click: "action",
      fill: "input",
      focus: "control",
      press: "action",
      select: "control",
      type: "input",
      wheel: "viewport",
    },
    actions: ["click", "fill", "focus", "press", "select", "type", "wheel"],
    events: [
      "a3s:device-change",
      "a3s:device-navigate",
      "a3s:device-preview-request",
      "basecoat:initialized",
    ],
    states: ["ready", "loading", "error"],
  }),
];
