import { defineComponent } from "../define.js";

export const interactionComponents = [
  defineComponent({
    slug: "back-to-bottom",
    name: "Back to Bottom",
    category: "navigation",
    selector: ".back-to-bottom",
    tag: "button",
    className: "back-to-bottom",
    attributes: { type: "button" },
    parts: { count: "[data-unread-count]", label: "[data-back-to-bottom-label]" },
    actions: ["click", "focus", "press"],
    events: [
      "a3s:back-to-bottom-activate",
      "a3s:back-to-bottom-visibility-change",
      "basecoat:initialized",
    ],
    methods: ["getState", "scrollToBottom", "setUnread"],
    states: ["hidden", "visible", "unread"],
  }),
  defineComponent({
    slug: "collapsible",
    name: "Collapsible",
    category: "data-display",
    selector: "details.collapsible",
    tag: "details",
    className: "collapsible",
    parts: { content: ":scope > [data-collapsible-content]", trigger: ":scope > summary" },
    actions: ["click", "focus", "press"],
    actionParts: { click: "trigger", focus: "trigger", press: "trigger" },
    events: ["toggle"],
    states: ["open", "closed", "disabled"],
  }),
  defineComponent({
    slug: "copy-button",
    name: "Copy Button",
    category: "actions",
    selector: ".copy-button",
    tag: "button",
    className: "btn copy-button",
    attributes: { type: "button" },
    parts: { feedback: "[data-copy-feedback]", label: "[data-copy-label]" },
    actions: ["click", "focus", "press"],
    events: [
      "a3s:copy-before",
      "a3s:copy-error",
      "a3s:copy-success",
      "basecoat:initialized",
    ],
    hooks: ["a3s:copy-before"],
    methods: ["copy", "getState", "setSource"],
    states: ["ready", "copying", "copied", "error", "disabled"],
  }),
  defineComponent({
    slug: "date-picker",
    name: "Date Picker",
    category: "forms",
    selector: "input.date-picker",
    tag: "input",
    className: "input date-picker",
    attributes: { type: "date" },
    actions: ["fill", "focus", "press", "select"],
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid", "read-only"],
  }),
  defineComponent({
    slug: "editable-text",
    name: "Editable Text",
    category: "forms",
    selector: ".editable-text",
    className: "editable-text",
    parts: {
      action: "[data-editable-action]",
      display: "[data-editable-display]",
      form: "[data-editable-form]",
      input: "input, textarea",
    },
    actions: ["click", "fill", "focus", "press"],
    actionParts: { click: "action", fill: "input", focus: "input", press: "input" },
    events: [
      "a3s:editable-text-before-commit",
      "a3s:editable-text-cancel",
      "a3s:editable-text-change",
      "a3s:editable-text-edit",
      "basecoat:initialized",
    ],
    hooks: ["a3s:editable-text-before-commit"],
    methods: ["beginEdit", "cancel", "commit", "getState", "setValue"],
    states: ["display", "editing", "saving", "error", "disabled"],
  }),
  defineComponent({
    slug: "emoji-picker",
    name: "Emoji Picker",
    category: "forms",
    selector: ".emoji-picker",
    tag: "section",
    className: "emoji-picker",
    parts: {
      empty: "[data-emoji-empty]",
      grid: "[data-emoji-grid]",
      input: "input[type=search]",
      option: "[data-emoji-value]",
    },
    actions: ["click", "fill", "focus", "press", "select"],
    actionParts: { click: "option", fill: "input", focus: "input", press: "option", select: "option" },
    events: [
      "a3s:emoji-before-select",
      "a3s:emoji-query-change",
      "a3s:emoji-select",
      "basecoat:initialized",
    ],
    hooks: ["a3s:emoji-before-select"],
    methods: ["getState", "refresh", "select", "setQuery"],
    states: ["ready", "empty", "disabled"],
  }),
  defineComponent({
    slug: "floating-panel",
    name: "Floating Panel",
    category: "overlays",
    selector: ".floating-panel",
    tag: "aside",
    className: "floating-panel",
    parts: {
      action: "button, a[href]",
      content: ":scope > section",
      header: ":scope > header",
      resizeHandle: "[data-floating-panel-resize]",
    },
    actions: ["click", "focus", "press"],
    events: [
      "a3s:floating-panel-before-close",
      "a3s:floating-panel-before-open",
      "a3s:floating-panel-close",
      "a3s:floating-panel-open",
      "basecoat:initialized",
    ],
    hooks: ["a3s:floating-panel-before-close", "a3s:floating-panel-before-open"],
    methods: ["close", "getState", "open", "toggle"],
    states: ["open", "closed", "floating", "docked", "sheet"],
  }),
  defineComponent({
    slug: "form",
    name: "Form",
    category: "forms",
    selector: "form.form",
    tag: "form",
    className: "form",
    parts: {
      action: ":scope > footer button, [type=submit], [type=reset]",
      error: "[data-form-error], [role=alert]",
      field: ".field, [data-form-field]",
      summary: "[data-form-summary]",
    },
    actions: ["click", "fill", "focus", "press"],
    events: ["reset", "submit"],
    states: ["ready", "submitting", "success", "invalid", "error", "read-only"],
  }),
  defineComponent({
    slug: "hotkey-input",
    name: "Hotkey Input",
    category: "forms",
    selector: ".hotkey-input",
    className: "hotkey-input",
    parts: { clear: "[data-hotkey-clear]", input: "input", preview: "[data-hotkey-preview]" },
    actions: ["click", "focus", "press"],
    actionParts: { click: "clear", focus: "input", press: "input" },
    events: [
      "a3s:hotkey-before-change",
      "a3s:hotkey-change",
      "a3s:hotkey-recording-change",
      "basecoat:initialized",
    ],
    hooks: ["a3s:hotkey-before-change"],
    methods: ["clear", "getValue", "setValue", "start", "stop"],
    states: ["ready", "recording", "disabled", "invalid"],
  }),
  defineComponent({
    slug: "image-viewer",
    name: "Image Viewer",
    category: "overlays",
    selector: "dialog.image-viewer",
    tag: "dialog",
    className: "image-viewer",
    parts: {
      action: "button",
      caption: "figcaption, [data-image-viewer-caption]",
      image: "img",
      toolbar: "[data-image-viewer-toolbar]",
    },
    actions: ["click", "focus", "press", "wheel"],
    actionParts: { click: "action", focus: "action", press: "action", wheel: "image" },
    events: [
      "a3s:image-viewer-before-open",
      "a3s:image-viewer-change",
      "a3s:image-viewer-open",
      "basecoat:initialized",
      "cancel",
      "close",
    ],
    hooks: ["a3s:image-viewer-before-open"],
    methods: ["close", "getState", "open", "reset", "rotate", "zoom"],
    states: ["open", "closed", "loading", "error"],
  }),
  defineComponent({
    slug: "sortable-list",
    name: "Sortable List",
    category: "data-display",
    selector: ".sortable-list",
    tag: "ol",
    className: "sortable-list",
    parts: { handle: "[data-sortable-handle]", item: "[data-sortable-item]", status: "[data-sortable-status]" },
    actions: ["drag", "focus", "press"],
    actionParts: { drag: "handle", focus: "handle", press: "handle" },
    events: [
      "a3s:sortable-before-reorder",
      "a3s:sortable-cancel",
      "a3s:sortable-reorder",
      "basecoat:initialized",
    ],
    hooks: ["a3s:sortable-before-reorder"],
    methods: ["cancel", "getOrder", "move", "refresh"],
    states: ["ready", "dragging", "keyboard", "disabled"],
  }),
  defineComponent({
    slug: "table-of-contents",
    name: "Table of Contents",
    category: "navigation",
    selector: ".table-of-contents",
    tag: "nav",
    className: "table-of-contents",
    attributes: { "aria-label": "On this page" },
    parts: { current: "[aria-current=location]", link: "a[href^='#']", list: "ol, ul" },
    actions: ["click", "focus"],
    actionParts: { click: "link", focus: "link" },
    events: ["a3s:table-of-contents-change", "basecoat:initialized"],
    methods: ["getState", "refresh", "setCurrent"],
    states: ["ready", "current"],
  }),
];
