import { defineComponent } from "../define.js";

export const navigationComponents = [
  defineComponent({
    slug: "activity-bar",
    name: "Activity Bar",
    category: "navigation",
    selector: ".activity-bar",
    tag: "aside",
    className: "activity-bar",
    parts: {
      action: "button, a[href]",
      footer: ":scope > footer",
      header: ":scope > header",
      navigation: ":scope > nav",
    },
    actions: ["click", "focus"],
    actionParts: { click: "action", focus: "action" },
    states: ["ready", "current"],
  }),
  defineComponent({
    slug: "breadcrumb",
    name: "Breadcrumb",
    category: "navigation",
    selector: ".breadcrumb",
    tag: "nav",
    className: "breadcrumb",
    attributes: { "aria-label": "Breadcrumb" },
    parts: { current: "[aria-current=page]", item: "li", link: "a[href]" },
    actions: ["click", "focus"],
    actionParts: { click: "link", focus: "link" },
    states: ["ready"],
  }),
  defineComponent({
    slug: "tabs",
    name: "Tabs",
    category: "navigation",
    selector: ".tabs",
    className: "tabs",
    parts: {
      list: "[role=tablist]",
      panel: "[role=tabpanel]",
      tab: "[role=tab]",
    },
    actions: ["click", "focus", "press"],
    actionParts: { click: "tab", focus: "tab", press: "tab" },
    events: ["basecoat:initialized"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "pagination",
    name: "Pagination",
    category: "navigation",
    selector: ".pagination",
    tag: "nav",
    className: "pagination",
    attributes: { "aria-label": "Pagination" },
    parts: {
      current: "[aria-current=page]",
      next: "[data-pagination-direction=next]",
      page: "a[href], button",
      previous: "[data-pagination-direction=previous]",
    },
    actions: ["click", "focus"],
    actionParts: { click: "page", focus: "page" },
    states: ["ready"],
  }),
  defineComponent({
    slug: "sidebar",
    name: "Sidebar",
    category: "navigation",
    selector: ".sidebar",
    tag: "aside",
    className: "sidebar",
    parts: {
      action: "nav a[href], nav button, nav summary",
      current: "[aria-current=page]",
      navigation: "nav",
      trigger: "[data-sidebar-trigger], button[aria-controls]",
    },
    actions: ["click", "focus", "press"],
    actionParts: { click: "action", focus: "action", press: "action" },
    events: ["basecoat:initialized"],
    states: ["ready", "expanded", "collapsed", "hidden"],
  }),
];

export const overlayComponents = [
  defineComponent({
    slug: "alert-dialog",
    name: "Alert Dialog",
    category: "overlays",
    selector: "dialog.alert-dialog",
    tag: "dialog",
    className: "alert-dialog",
    attributes: { role: "alertdialog" },
    parts: {
      action: "button, .btn",
      description: "[aria-describedby]",
      title: "[aria-labelledby]",
    },
    actions: ["click", "focus", "press"],
    events: ["cancel", "close"],
    states: ["open", "closed"],
  }),
  defineComponent({
    slug: "dialog",
    name: "Dialog",
    category: "overlays",
    selector: "dialog.dialog",
    tag: "dialog",
    className: "dialog",
    parts: {
      action: "button, .btn",
      content: ":scope > div, :scope > article",
      description: "[aria-describedby]",
      title: "[aria-labelledby]",
    },
    actions: ["click", "fill", "focus", "press"],
    events: ["cancel", "close"],
    states: ["open", "closed"],
  }),
  defineComponent({
    slug: "drawer",
    name: "Drawer",
    category: "overlays",
    selector: "dialog.drawer",
    tag: "dialog",
    className: "drawer",
    parts: {
      action: "button, .btn",
      content: ":scope > article",
      title: "[aria-labelledby]",
    },
    actions: ["click", "focus", "press"],
    events: ["cancel", "close"],
    states: ["open", "closed"],
  }),
  defineComponent({
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    category: "overlays",
    selector: ".dropdown-menu",
    className: "dropdown-menu",
    parts: {
      item: "[role^=menuitem]",
      menu: "[role=menu]",
      trigger: "button[aria-haspopup=menu]",
    },
    actions: ["click", "focus", "press", "select"],
    actionParts: { select: "item" },
    events: ["basecoat:initialized"],
    states: ["expanded", "collapsed", "disabled"],
  }),
  defineComponent({
    slug: "popover",
    name: "Popover",
    category: "overlays",
    selector: ".popover",
    className: "popover",
    parts: {
      content: "[data-popover]",
      trigger: "button[aria-controls]",
    },
    actions: ["click", "focus", "press"],
    events: ["basecoat:initialized"],
    states: ["expanded", "collapsed"],
  }),
  defineComponent({
    slug: "command",
    name: "Command",
    category: "overlays",
    selector: ".command",
    className: "command",
    parts: {
      empty: "[data-command-empty]",
      group: "[role=group]",
      input: "input",
      item: "[role=option], [role^=menuitem], [data-command-item]",
      list: "[role=listbox]",
    },
    actions: ["click", "fill", "focus", "press", "select"],
    actionParts: { click: "item", select: "item" },
    events: ["basecoat:initialized"],
    states: ["ready", "empty", "loading", "open", "closed"],
  }),
  defineComponent({
    slug: "tooltip",
    name: "Tooltip",
    category: "overlays",
    selector: "[data-tooltip]",
    tag: "button",
    attributes: { "data-tooltip": "Tooltip", type: "button" },
    parts: { trigger: ":scope" },
    actions: ["focus", "hover"],
    states: ["ready", "disabled"],
  }),
];
