import { defineComponent } from "../define.js";

export const actionComponents = [
  defineComponent({
    slug: "button",
    name: "Button",
    category: "actions",
    selector: ".btn",
    tag: "button",
    className: "btn",
    attributes: { type: "button" },
    actions: ["click", "focus"],
    states: ["ready", "disabled", "loading", "pressed"],
  }),
  defineComponent({
    slug: "button-group",
    name: "Button Group",
    category: "actions",
    selector: ".button-group",
    className: "button-group",
    parts: { action: ":scope > button, :scope > a, :scope > .btn" },
    actions: ["focus", "click"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "bulk-action-bar",
    name: "Bulk Action Bar",
    category: "actions",
    selector: ".bulk-action-bar",
    tag: "section",
    className: "bulk-action-bar",
    attributes: { "aria-label": "Selected item actions", role: "region" },
    parts: {
      action: "[data-bulk-actions] button, [data-bulk-actions] a[href]",
      actions: "[data-bulk-actions]",
      clear: "[data-bulk-clear]",
      selection: "[data-bulk-selection]",
      summary: "[data-bulk-summary]",
    },
    actions: ["click", "focus", "press"],
    actionParts: { click: "action", focus: "action", press: "action" },
    states: ["empty", "selected", "loading", "disabled"],
  }),
];

export const formComponents = [
  defineComponent({
    slug: "field",
    name: "Field",
    category: "forms",
    selector: ".field",
    className: "field",
    parts: {
      control: "input, textarea, select, [role=combobox]",
      description: ":scope > p, [data-field-description]",
      label: "label, legend",
      message: "[data-field-message]",
    },
    states: ["ready", "disabled", "invalid", "readonly"],
  }),
  defineComponent({
    slug: "filter-bar",
    name: "Filter Bar",
    category: "forms",
    selector: ".filter-bar",
    tag: "form",
    className: "filter-bar",
    attributes: { "aria-label": "Filters", role: "search" },
    parts: {
      active: "[data-filter-active]",
      clear: "[data-filter-clear]",
      count: "[data-filter-count]",
      search:
        "input[data-filter-search], textarea[data-filter-search], [data-filter-search] input, [data-filter-search] textarea",
      toggle: "[data-filter-toggle]",
    },
    actions: ["click", "fill", "focus", "press", "type"],
    actionParts: {
      click: "toggle",
      fill: "search",
      focus: "search",
      press: "toggle",
      type: "search",
    },
    events: ["a3s:filter-change", "basecoat:initialized", "input"],
    states: ["ready", "active", "empty", "disabled", "loading"],
  }),
  defineComponent({
    slug: "input",
    name: "Input",
    category: "forms",
    selector:
      "input.input:not([type=checkbox]):not([type=radio]):not([type=range])",
    tag: "input",
    className: "input",
    attributes: { type: "text" },
    actions: ["fill", "focus", "type"],
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid", "readonly"],
  }),
  defineComponent({
    slug: "input-group",
    name: "Input Group",
    category: "forms",
    selector: ".input-group",
    className: "input-group",
    parts: {
      action: "button, .btn",
      control: "input, textarea, select",
      prefix: "[data-align=start]",
      suffix: "[data-align=end]",
    },
    actions: ["fill", "focus", "type"],
    states: ["ready", "disabled", "invalid", "loading"],
  }),
  defineComponent({
    slug: "textarea",
    name: "Textarea",
    category: "forms",
    selector: "textarea.textarea",
    tag: "textarea",
    className: "textarea",
    actions: ["fill", "focus", "type"],
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid", "readonly"],
  }),
  defineComponent({
    slug: "code-editor",
    name: "Code Editor",
    category: "harness",
    selector: ".code-editor",
    className: "code-editor",
    attributes: { role: "group" },
    parts: {
      control: "textarea",
      gutter: "[data-code-editor-gutter]",
      message: "[data-code-editor-message]",
      position: "[data-code-editor-position]",
      status: "[data-code-editor-state]",
    },
    actions: ["fill", "focus", "press", "type"],
    events: ["a3s:code-clean", "a3s:code-save"],
    states: ["ready", "dirty", "invalid", "readonly"],
  }),
  defineComponent({
    slug: "native-select",
    name: "Native Select",
    category: "forms",
    selector: "select.select",
    tag: "select",
    className: "select",
    actions: ["focus", "select"],
    events: ["change", "input"],
    states: ["ready", "disabled", "invalid"],
  }),
  defineComponent({
    slug: "select",
    name: "Select",
    category: "forms",
    selector: ".select:not(select)",
    className: "select",
    parts: {
      option: "[role=option]",
      popup: "[role=listbox], [data-popover]",
      trigger: "button[aria-haspopup=listbox]",
      value: "button[aria-haspopup=listbox] > span",
    },
    actions: ["click", "focus", "press", "select"],
    events: ["change"],
    states: ["ready", "disabled", "expanded", "collapsed", "invalid"],
  }),
  defineComponent({
    slug: "checkbox",
    name: "Checkbox",
    category: "forms",
    selector: "input.input[type=checkbox]:not([role=switch])",
    tag: "input",
    className: "input",
    attributes: { type: "checkbox" },
    actions: ["check", "focus", "uncheck"],
    events: ["change", "input"],
    states: ["checked", "unchecked", "indeterminate", "disabled"],
  }),
  defineComponent({
    slug: "radio-group",
    name: "Radio Group",
    category: "forms",
    selector: "[role=radiogroup], [data-slot=radio-group]",
    attributes: { role: "radiogroup" },
    parts: { option: "input[type=radio]", label: "label" },
    actions: ["check", "focus", "press"],
    actionParts: { focus: "option", press: "option" },
    events: ["change", "input"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "switch",
    name: "Switch",
    category: "forms",
    selector: "input.input[role=switch]",
    tag: "input",
    className: "input",
    attributes: { role: "switch", type: "checkbox" },
    actions: ["check", "focus", "uncheck"],
    events: ["change", "input"],
    states: ["checked", "unchecked", "disabled"],
  }),
  defineComponent({
    slug: "slider",
    name: "Slider",
    category: "forms",
    selector: "input.input[type=range]",
    tag: "input",
    className: "input",
    attributes: { max: "100", min: "0", type: "range", value: "50" },
    actions: ["focus", "press"],
    events: ["change", "input"],
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "label",
    name: "Label",
    category: "forms",
    selector: ".label",
    tag: "label",
    className: "label",
    parts: { control: "input, textarea, select" },
    actions: ["click"],
    actionParts: { click: "control" },
    states: ["ready", "disabled"],
  }),
  defineComponent({
    slug: "combobox",
    name: "Combobox",
    category: "forms",
    selector: ".combobox",
    className: "combobox",
    parts: {
      clear: "[data-combobox-clear]",
      input: "input[role=combobox]",
      option: "[role=option]",
      popup: "[role=listbox], [data-popover]",
      trigger: "button[aria-haspopup=listbox]",
    },
    actions: ["click", "fill", "focus", "press", "select"],
    events: ["change", "input"],
    states: ["ready", "disabled", "expanded", "collapsed", "invalid"],
  }),
];

export const utilityComponents = [
  defineComponent({
    slug: "scroll-area",
    name: "Scroll Area",
    category: "utilities",
    selector: ".scrollbar, .scrollbar-sm",
    className: "scrollbar",
    attributes: { tabindex: "0" },
    actions: ["focus", "wheel"],
    events: ["scroll"],
    states: ["ready"],
  }),
  defineComponent({
    slug: "theme-switcher",
    name: "Theme Switcher",
    category: "utilities",
    selector:
      '[data-a3s-theme-toggle], button[onclick*=".theme.toggle"], button[data-preview-onclick*=".theme.toggle"]',
    tag: "button",
    className: "btn",
    attributes: { "data-a3s-theme-toggle": "", type: "button" },
    actions: ["click", "focus"],
    events: ["a3s:themechange"],
    states: ["ready", "light", "dark"],
  }),
];
