import type { ProductLocalizedText } from "./product-playground-data";

export type ProductFileEntry = {
  favorite?: boolean;
  id: string;
  kind: "file" | "folder";
  modified: string;
  name: string;
  owner: string;
  parentId: string | null;
  preview?: ProductLocalizedText;
  size: string;
  sizeBytes: number;
  type: string;
};

export const productFileEntries: readonly ProductFileEntry[] = [
  {
    id: "root",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "A3S UI",
    owner: "Local",
    parentId: null,
    size: "—",
    sizeBytes: 0,
    type: "Folder",
  },
  {
    id: "design-system",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "Design system",
    owner: "You",
    parentId: "root",
    size: "42 items",
    sizeBytes: 42,
    type: "Folder",
    favorite: true,
  },
  {
    id: "documentation",
    kind: "folder",
    modified: "2026-08-18T09:18:00.000Z",
    name: "Documentation",
    owner: "You",
    parentId: "root",
    size: "86 items",
    sizeBytes: 86,
    type: "Folder",
    favorite: true,
  },
  {
    id: "test-evidence",
    kind: "folder",
    modified: "2026-08-18T08:35:00.000Z",
    name: "Test evidence",
    owner: "Automation",
    parentId: "root",
    size: "18 items",
    sizeBytes: 18,
    type: "Folder",
  },
  {
    id: "release-readiness",
    kind: "file",
    modified: "2026-08-18T10:21:00.000Z",
    name: "release-readiness.md",
    owner: "You",
    parentId: "root",
    preview: {
      en: "# Release readiness\n\nAll public contracts must agree across source, adapters, documentation, and browser evidence.",
      zh: "# 发布就绪\n\n公开契约必须在源码、适配器、文档和浏览器证据之间保持一致。",
    },
    size: "8 KB",
    sizeBytes: 8_192,
    type: "Markdown",
    favorite: true,
  },
  {
    id: "component-inventory",
    kind: "file",
    modified: "2026-08-17T16:42:00.000Z",
    name: "component-inventory.csv",
    owner: "Mina",
    parentId: "root",
    preview: {
      en: "component,status,owner\nagent-composer,in review,product\nfile-manager,planned,design-system",
      zh: "component,status,owner\nagent-composer,评审中,product\nfile-manager,已规划,design-system",
    },
    size: "24 KB",
    sizeBytes: 24_576,
    type: "CSV",
  },
  {
    id: "device-shell-review",
    kind: "file",
    modified: "2026-08-17T14:12:00.000Z",
    name: "device-shell-review.png",
    owner: "Rui",
    parentId: "root",
    preview: {
      en: "Visual evidence for phone, tablet, laptop, and desktop device shells.",
      zh: "手机、平板、笔记本与桌面设备外壳的视觉验收证据。",
    },
    size: "1.8 MB",
    sizeBytes: 1_887_437,
    type: "PNG image",
  },
  {
    id: "components",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "components",
    owner: "You",
    parentId: "design-system",
    size: "28 items",
    sizeBytes: 28,
    type: "Folder",
  },
  {
    id: "integrations",
    kind: "folder",
    modified: "2026-08-18T10:18:00.000Z",
    name: "integrations",
    owner: "You",
    parentId: "design-system",
    size: "6 items",
    sizeBytes: 6,
    type: "Folder",
  },
  {
    id: "agent-composer-css",
    kind: "file",
    modified: "2026-08-18T10:42:00.000Z",
    name: "agent-composer.css",
    owner: "You",
    parentId: "components",
    preview: {
      en: ".agent-composer {\n  display: grid;\n  min-width: 0;\n  overflow: visible;\n}",
      zh: ".agent-composer {\n  display: grid;\n  min-width: 0;\n  overflow: visible;\n}",
    },
    size: "5.8 KB",
    sizeBytes: 5_939,
    type: "CSS",
    favorite: true,
  },
  {
    id: "file-manager-css",
    kind: "file",
    modified: "2026-08-18T10:11:00.000Z",
    name: "file-manager.css",
    owner: "You",
    parentId: "components",
    preview: {
      en: ".file-manager {\n  display: grid;\n  grid-template-columns: auto minmax(0, 1fr);\n}",
      zh: ".file-manager {\n  display: grid;\n  grid-template-columns: auto minmax(0, 1fr);\n}",
    },
    size: "4.9 KB",
    sizeBytes: 5_018,
    type: "CSS",
  },
  {
    id: "react-adapter",
    kind: "file",
    modified: "2026-08-18T10:18:00.000Z",
    name: "react.js",
    owner: "You",
    parentId: "integrations",
    preview: {
      en: "export function useAgentComposerEditor(options = {}) {\n  // Shared TipTap contract\n}",
      zh: "export function useAgentComposerEditor(options = {}) {\n  // 共享 TipTap 契约\n}",
    },
    size: "7.4 KB",
    sizeBytes: 7_578,
    type: "JavaScript",
  },
  {
    id: "zh-docs",
    kind: "folder",
    modified: "2026-08-18T09:18:00.000Z",
    name: "简体中文",
    owner: "You",
    parentId: "documentation",
    size: "43 pages",
    sizeBytes: 43,
    type: "Folder",
  },
  {
    id: "en-docs",
    kind: "folder",
    modified: "2026-08-18T09:12:00.000Z",
    name: "English",
    owner: "You",
    parentId: "documentation",
    size: "43 pages",
    sizeBytes: 43,
    type: "Folder",
  },
  {
    id: "agent-composer-doc",
    kind: "file",
    modified: "2026-08-18T09:18:00.000Z",
    name: "agent-composer.mdx",
    owner: "You",
    parentId: "zh-docs",
    preview: {
      en: "Production composer contract with HTML, React, Vue, and keyboard acceptance criteria.",
      zh: "包含 HTML、React、Vue 与键盘验收标准的生产级输入器契约。",
    },
    size: "12 KB",
    sizeBytes: 12_288,
    type: "MDX",
  },
  {
    id: "desktop-evidence",
    kind: "file",
    modified: "2026-08-18T08:35:00.000Z",
    name: "project-desktop.png",
    owner: "Automation",
    parentId: "test-evidence",
    preview: {
      en: "Desktop visual acceptance at 1440 × 960.",
      zh: "1440 × 960 桌面端视觉验收。",
    },
    size: "824 KB",
    sizeBytes: 843_776,
    type: "PNG image",
  },
  {
    id: "mobile-evidence",
    kind: "file",
    modified: "2026-08-18T08:31:00.000Z",
    name: "project-mobile.png",
    owner: "Automation",
    parentId: "test-evidence",
    preview: {
      en: "Mobile visual acceptance at 390 × 844.",
      zh: "390 × 844 移动端视觉验收。",
    },
    size: "462 KB",
    sizeBytes: 473_088,
    type: "PNG image",
  },
];
