import type { ProductLocalizedText } from "./product-playground-data";

export type ProductFileWorkbenchKind =
  "code" | "document" | "pdf" | "presentation" | "spreadsheet";

export type ProductFileEntry = {
  favorite?: boolean;
  id: string;
  kind: "file" | "folder";
  modified: string;
  name: string;
  owner: string;
  parentId: string | null;
  preview?: ProductLocalizedText;
  size: string;
  sizeBytes: number;
  type: string;
  workbench?: ProductFileWorkbenchKind;
};

export const productFileEntries: readonly ProductFileEntry[] = [
  {
    id: "root",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "A3S UI",
    owner: "Local",
    parentId: null,
    size: "—",
    sizeBytes: 0,
    type: "Folder",
  },
  {
    id: "design-system",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "Design system",
    owner: "You",
    parentId: "root",
    size: "42 items",
    sizeBytes: 42,
    type: "Folder",
    favorite: true,
  },
  {
    id: "documentation",
    kind: "folder",
    modified: "2026-08-18T09:18:00.000Z",
    name: "Documentation",
    owner: "You",
    parentId: "root",
    size: "86 items",
    sizeBytes: 86,
    type: "Folder",
    favorite: true,
  },
  {
    id: "test-evidence",
    kind: "folder",
    modified: "2026-08-18T08:35:00.000Z",
    name: "Test evidence",
    owner: "Automation",
    parentId: "root",
    size: "18 items",
    sizeBytes: 18,
    type: "Folder",
  },
  {
    id: "release-readiness",
    kind: "file",
    modified: "2026-08-18T10:21:00.000Z",
    name: "release-readiness.md",
    owner: "You",
    parentId: "root",
    preview: {
      en: "# Release readiness\n\nAll public contracts must agree across source, adapters, documentation, and browser evidence.",
      zh: "# 发布就绪\n\n公开契约必须在源码、适配器、文档和浏览器证据之间保持一致。",
    },
    size: "8 KB",
    sizeBytes: 8_192,
    type: "Markdown",
    favorite: true,
    workbench: "code",
  },
  {
    id: "component-inventory",
    kind: "file",
    modified: "2026-08-17T16:42:00.000Z",
    name: "component-inventory.csv",
    owner: "Mina",
    parentId: "root",
    preview: {
      en: "component,status,owner\nagent-composer,in review,product\nfile-manager,planned,design-system",
      zh: "component,status,owner\nagent-composer,评审中,product\nfile-manager,已规划,design-system",
    },
    size: "24 KB",
    sizeBytes: 24_576,
    type: "CSV",
    workbench: "spreadsheet",
  },
  {
    id: "experience-brief",
    kind: "file",
    modified: "2026-08-18T10:36:00.000Z",
    name: "experience-brief.docx",
    owner: "You",
    parentId: "root",
    preview: {
      en: "Product experience brief with goals, acceptance criteria, cited evidence, and tracked review decisions.",
      zh: "包含目标、验收标准、引用证据与修订决策的产品体验说明。",
    },
    size: "86 KB",
    sizeBytes: 88_064,
    type: "Word document",
    workbench: "document",
  },
  {
    id: "quality-scorecard",
    kind: "file",
    modified: "2026-08-18T10:29:00.000Z",
    name: "quality-scorecard.xlsx",
    owner: "Mina",
    parentId: "root",
    preview: {
      en: "Acceptance scorecard covering interaction, accessibility, responsiveness, and visual consistency.",
      zh: "覆盖交互、可访问性、响应式与视觉一致性的验收评分表。",
    },
    size: "124 KB",
    sizeBytes: 126_976,
    type: "Excel workbook",
    workbench: "spreadsheet",
  },
  {
    id: "release-review",
    kind: "file",
    modified: "2026-08-18T10:17:00.000Z",
    name: "release-review.pptx",
    owner: "Rui",
    parentId: "root",
    preview: {
      en: "Release review deck with product decisions, before-and-after evidence, and rollout steps.",
      zh: "包含产品决策、前后对比证据与发布步骤的评审演示文稿。",
    },
    size: "2.4 MB",
    sizeBytes: 2_516_582,
    type: "PowerPoint presentation",
    workbench: "presentation",
  },
  {
    id: "visual-acceptance-report",
    kind: "file",
    modified: "2026-08-18T09:54:00.000Z",
    name: "visual-acceptance-report.pdf",
    owner: "Automation",
    parentId: "root",
    preview: {
      en: "Bounded visual acceptance report with desktop, mobile, focus, and overlay evidence.",
      zh: "包含桌面、移动、焦点与浮层证据的视觉验收报告。",
    },
    size: "3.8 MB",
    sizeBytes: 3_984_588,
    type: "PDF document",
    workbench: "pdf",
  },
  {
    id: "device-shell-review",
    kind: "file",
    modified: "2026-08-17T14:12:00.000Z",
    name: "device-shell-review.png",
    owner: "Rui",
    parentId: "root",
    preview: {
      en: "Visual evidence for phone, tablet, laptop, and desktop device shells.",
      zh: "手机、平板、笔记本与桌面设备外壳的视觉验收证据。",
    },
    size: "1.8 MB",
    sizeBytes: 1_887_437,
    type: "PNG image",
  },
  {
    id: "device-shell-review-html",
    kind: "file",
    modified: "2026-08-17T14:08:00.000Z",
    name: "device-shell-review.html",
    owner: "Rui",
    parentId: "root",
    preview: {
      en: '<main class="device-review">\n  <h1>Device shell acceptance</h1>\n  <p>Phone, tablet, laptop, and desktop frames preserve the selected CSS viewport.</p>\n</main>',
      zh: '<main class="device-review">\n  <h1>设备外壳验收</h1>\n  <p>手机、平板、笔记本与桌面外壳会保留所选 CSS 视口。</p>\n</main>',
    },
    size: "19 KB",
    sizeBytes: 19_456,
    type: "HTML document",
    workbench: "code",
  },
  {
    id: "components",
    kind: "folder",
    modified: "2026-08-18T10:42:00.000Z",
    name: "components",
    owner: "You",
    parentId: "design-system",
    size: "28 items",
    sizeBytes: 28,
    type: "Folder",
  },
  {
    id: "integrations",
    kind: "folder",
    modified: "2026-08-18T10:18:00.000Z",
    name: "integrations",
    owner: "You",
    parentId: "design-system",
    size: "6 items",
    sizeBytes: 6,
    type: "Folder",
  },
  {
    id: "agent-composer-css",
    kind: "file",
    modified: "2026-08-18T10:42:00.000Z",
    name: "agent-composer.css",
    owner: "You",
    parentId: "components",
    preview: {
      en: ".agent-composer {\n  display: grid;\n  min-width: 0;\n  overflow: visible;\n}",
      zh: ".agent-composer {\n  display: grid;\n  min-width: 0;\n  overflow: visible;\n}",
    },
    size: "5.8 KB",
    sizeBytes: 5_939,
    type: "CSS",
    favorite: true,
    workbench: "code",
  },
  {
    id: "file-manager-css",
    kind: "file",
    modified: "2026-08-18T10:11:00.000Z",
    name: "file-manager.css",
    owner: "You",
    parentId: "components",
    preview: {
      en: ".file-manager {\n  display: grid;\n  grid-template-columns: auto minmax(0, 1fr);\n}",
      zh: ".file-manager {\n  display: grid;\n  grid-template-columns: auto minmax(0, 1fr);\n}",
    },
    size: "4.9 KB",
    sizeBytes: 5_018,
    type: "CSS",
    workbench: "code",
  },
  {
    id: "react-adapter",
    kind: "file",
    modified: "2026-08-18T10:18:00.000Z",
    name: "react.js",
    owner: "You",
    parentId: "integrations",
    preview: {
      en: "export function useAgentComposerEditor(options = {}) {\n  // Shared TipTap contract\n}",
      zh: "export function useAgentComposerEditor(options = {}) {\n  // 共享 TipTap 契约\n}",
    },
    size: "7.4 KB",
    sizeBytes: 7_578,
    type: "JavaScript",
    workbench: "code",
  },
  {
    id: "zh-docs",
    kind: "folder",
    modified: "2026-08-18T09:18:00.000Z",
    name: "简体中文",
    owner: "You",
    parentId: "documentation",
    size: "43 pages",
    sizeBytes: 43,
    type: "Folder",
  },
  {
    id: "en-docs",
    kind: "folder",
    modified: "2026-08-18T09:12:00.000Z",
    name: "English",
    owner: "You",
    parentId: "documentation",
    size: "43 pages",
    sizeBytes: 43,
    type: "Folder",
  },
  {
    id: "agent-composer-doc",
    kind: "file",
    modified: "2026-08-18T09:18:00.000Z",
    name: "agent-composer.mdx",
    owner: "You",
    parentId: "zh-docs",
    preview: {
      en: "Production composer contract with HTML, React, Vue, and keyboard acceptance criteria.",
      zh: "包含 HTML、React、Vue 与键盘验收标准的生产级输入器契约。",
    },
    size: "12 KB",
    sizeBytes: 12_288,
    type: "MDX",
    workbench: "code",
  },
  {
    id: "desktop-evidence",
    kind: "file",
    modified: "2026-08-18T08:35:00.000Z",
    name: "project-desktop.png",
    owner: "Automation",
    parentId: "test-evidence",
    preview: {
      en: "Desktop visual acceptance at 1440 × 960.",
      zh: "1440 × 960 桌面端视觉验收。",
    },
    size: "824 KB",
    sizeBytes: 843_776,
    type: "PNG image",
  },
  {
    id: "mobile-evidence",
    kind: "file",
    modified: "2026-08-18T08:31:00.000Z",
    name: "project-mobile.png",
    owner: "Automation",
    parentId: "test-evidence",
    preview: {
      en: "Mobile visual acceptance at 390 × 844.",
      zh: "390 × 844 移动端视觉验收。",
    },
    size: "462 KB",
    sizeBytes: 473_088,
    type: "PNG image",
  },
];
