import type { FormDocument } from '../../../src/core';

export const sampleForm: FormDocument = {
  kind: 'a3s.form',
  apiVersion: 'a3s.dev/form/v1alpha1',
  metadata: {
    title: '新员工入职申请',
    description: '收集入职资料并提交给人力资源团队审核。',
    locale: 'zh-CN',
    tags: ['人力资源', '审批'],
    owner: 'A3S Cloud',
  },
  revision: 1,
  schema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    properties: {
      name: { type: 'string', title: '姓名', minLength: 2, maxLength: 40 },
      email: { type: 'string', title: '企业邮箱', format: 'email' },
      department: {
        type: 'string',
        title: '所属部门',
        enum: ['product', 'engineering', 'design', 'operations'],
      },
      onboardingRecord: { type: 'string', title: '入职记录' },
      employmentType: {
        type: 'string',
        title: '用工类型',
        enum: ['full-time', 'intern', 'contractor'],
      },
      startDate: { type: 'string', title: '入职日期', format: 'date' },
      equipment: { type: 'boolean', title: '需要新设备' },
      note: { type: 'string', title: '补充说明', maxLength: 500 },
    },
    required: ['name', 'email', 'department', 'startDate'],
    additionalProperties: false,
  },
  ui: {
    root: 'root',
    nodes: [
      {
        id: 'root',
        kind: 'root',
        label: '入职信息',
        description: '带 * 的字段为必填项',
        columns: 12,
        children: [
          'name',
          'email',
          'department',
          'onboarding-record',
          'employment-type',
          'start-date',
          'equipment',
          'note',
        ],
      },
      {
        id: 'name',
        kind: 'field',
        label: '姓名',
        description: '请填写证件上的姓名',
        schemaPath: '/properties/name',
        widget: 'text',
        placeholder: '例如：张小明',
        width: 6,
      },
      {
        id: 'email',
        kind: 'field',
        label: '企业邮箱',
        description: '离开输入框时检查邮箱是否可用',
        schemaPath: '/properties/email',
        widget: 'email',
        placeholder: 'name@company.com',
        width: 6,
      },
      {
        id: 'department',
        kind: 'field',
        label: '所属部门',
        schemaPath: '/properties/department',
        widget: 'select',
        width: 6,
        options: [
          { label: '产品', value: 'product' },
          { label: '研发', value: 'engineering' },
          { label: '设计', value: 'design' },
          { label: '运营', value: 'operations' },
        ],
      },
      {
        id: 'onboarding-record',
        kind: 'field',
        label: '入职记录',
        description: '由姓名和部门自动生成',
        schemaPath: '/properties/onboardingRecord',
        widget: 'text',
        width: 12,
      },
      {
        id: 'employment-type',
        kind: 'field',
        label: '用工类型',
        schemaPath: '/properties/employmentType',
        widget: 'select',
        width: 6,
        options: [
          { label: '正式员工', value: 'full-time' },
          { label: '实习生', value: 'intern' },
          { label: '外部协作', value: 'contractor' },
        ],
      },
      {
        id: 'start-date',
        kind: 'field',
        label: '入职日期',
        schemaPath: '/properties/startDate',
        widget: 'date',
        width: 6,
      },
      {
        id: 'equipment',
        kind: 'field',
        label: '需要新设备',
        description: '开启后，IT 团队会准备标准开发设备。',
        schemaPath: '/properties/equipment',
        widget: 'switch',
        width: 6,
      },
      {
        id: 'note',
        kind: 'field',
        label: '补充说明',
        schemaPath: '/properties/note',
        widget: 'textarea',
        placeholder: '可填写设备偏好或其他需要关注的信息',
        width: 12,
      },
    ],
  },
  rules: [
    {
      id: 'derive-onboarding-record',
      target: 'onboarding-record',
      kind: 'computed',
      expression: {
        op: 'if',
        condition: {
          op: 'all',
          values: [
            { op: 'exists', value: { op: 'field', path: 'name' } },
            { op: 'exists', value: { op: 'field', path: 'department' } },
          ],
        },
        whenTrue: {
          op: 'concat',
          values: [
            { op: 'field', path: 'name' },
            { op: 'literal', value: ' · ' },
            { op: 'field', path: 'department' },
          ],
        },
        whenFalse: { op: 'literal', value: '' },
      },
    },
    {
      id: 'contractor-equipment',
      target: 'equipment',
      kind: 'visible',
      expression: {
        op: 'ne',
        left: { op: 'field', path: 'employmentType' },
        right: { op: 'literal', value: 'contractor' },
      },
    },
  ],
  actions: [
    { id: 'save-draft', registryKey: 'host.save-draft.v1', label: '保存草稿', tone: 'secondary' },
    { id: 'submit', registryKey: 'host.submit.v1', label: '提交申请', tone: 'primary' },
  ],
};
