import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const projectRoot = resolve(import.meta.dirname, '..');
const repositoryRoot = resolve(projectRoot, '../..');
const manifest = resolve(projectRoot, 'wasm/a3s-form-wasm/Cargo.toml');
const build = spawnSync(
  'cargo',
  ['build', '--manifest-path', manifest, '--target', 'wasm32v1-none', '--release'],
  { cwd: projectRoot, encoding: 'utf8', stdio: 'pipe' },
);

if (build.status !== 0) {
  process.stderr.write(build.stderr || build.stdout || 'WASM build failed.\n');
  process.exit(build.status ?? 1);
}

const source = resolve(
  projectRoot,
  'wasm/a3s-form-wasm/target/wasm32v1-none/release/a3s_form_wasm.wasm',
);
const binary = new Uint8Array(await readFile(source));
const wasmOutput = resolve(projectRoot, 'src/wasm/sha256.wasm');
const typescriptOutput = resolve(projectRoot, 'src/wasm/sha256-binary.ts');
await mkdir(dirname(wasmOutput), { recursive: true });
await writeFile(wasmOutput, binary);

const rows = [];
for (let index = 0; index < binary.length; index += 24) {
  rows.push(`  ${Array.from(binary.slice(index, index + 24)).join(', ')},`);
}
await writeFile(
  typescriptOutput,
  `// Generated by scripts/build-wasm.mjs. Do not edit by hand.\nexport const SHA256_WASM_BINARY = new Uint8Array([\n${rows.join('\n')}\n]);\n`,
);
const formatter = spawnSync(
  process.execPath,
  [
    resolve(repositoryRoot, 'node_modules/@biomejs/biome/bin/biome'),
    'format',
    '--write',
    typescriptOutput,
  ],
  { cwd: projectRoot, encoding: 'utf8', stdio: 'pipe' },
);
if (formatter.status !== 0) {
  process.stderr.write(formatter.stderr || formatter.stdout || 'WASM binding format failed.\n');
  process.exit(formatter.status ?? 1);
}
console.log(`Built WASM SHA-256 accelerator (${binary.length} bytes).`);
